# Github actions to build
# and push wheel files
on:
  push:
    branches:
      - main

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python and dependencies
        run: |
          uv venv --python=python3.11
          source .venv/bin/activate
          uv sync
      - name: Build wheel
        run: |
          uv build
      - name: Push wheel to PyPI
        run: |
          uv publish
        env:
          UV_PUBLISH_INDEX: testpypi
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
          UV_PUBLISH_CHECK_URL: https://test.pypi.org/legacy/
          UV_PUBLISH_URL: https://test.pypi.org/legacy/
